import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "First Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans bg-gray-50`}
      >
        <nav className="bg-dark shadow p-4">
          <Link href="/" className="mr-4 text-white-800 hover:border-b-2 border-white-800">Home</Link>
          <Link href="/about" className="text-white-800 hover:border-b-2 border-white-800">About</Link>
        </nav>
        <main>{children}</main>

      </body>
    </html>
  );
}
